# Generated by Django 6.0.2 on 2026-03-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_invoice_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
    ]
