# Generated by Django 6.0.2 on 2026-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_rename_created_at_invoice_date_invoice_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('plan_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], max_length=20),
        ),
    ]
