# Generated by Django 6.0.2 on 2026-03-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_subscription_rename_date_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
