# Generated by Django 6.0.2 on 2026-04-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_amount_subscription_total_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
