# Generated by Django 6.0.2 on 2026-03-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_subtotal_subscription_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price_per_day',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
