# Generated by Django 6.0.2 on 2026-03-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
