# Generated by Django 6.0.2 on 2026-03-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoiceitem_discount_invoiceitem_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
