# Generated by Django 6.0.2 on 2026-03-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_invoice_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='qr_code',
        ),
    ]
