# Generated by Django 6.0.2 on 2026-03-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
