# Generated by Django 6.0.2 on 2026-03-29 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_delete_subscription'),
        ('subscriptions', '0005_remove_subscription_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SUBSCRIPTION', 'Subscription')], default='PRODUCT', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
