# Generated by Django 6.0.2 on 2026-03-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Dairy', 'Dairy'), ('Snacks', 'Snacks'), ('Household', 'Household')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='P000', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('litre', 'Litre'), ('pack', 'Pack'), ('bag', 'Bag'), ('packet', 'Packet')], default='P000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
