# Generated by Django 6.0.2 on 2026-03-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Dairy', 'Dairy'), ('Snacks', 'Snacks'), ('Household', 'Household'), ('Bakery', 'Bakery')], max_length=50),
        ),
    ]
